nameOverride: k8s-spot-termination-handler

clusterName: eks

detachAsg: false

# tolerations:
#   - key: node-role
#     operator: Equal
#     value: scaling
#     effect: NoSchedule

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
#   iam.amazonaws.com/role: "eks-asg"

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: IAM_ROLE_ARN
